CLIENT_CONTROLLER_HOST: "0.0.0.0"
CLIENT_CONTROLLER_PORT: 4217
DEFAULT_SECRET_NAME: "dockerhubsecret"
DEFAULT_HARDWARE_ID: "defaultclusternode"
PRODUCTION_KUBECONFIG: "/root/.kube/config"
ASSESSMENT_KUBECONFIG: "/root/.kube/config-assessment"
DATACENTER_LABEL: "mlmec/DataCenter"
MONGO_SHARD_LABEL: "mlmec/MongoShard"
MONGOS_LABEL: "mlmec/MongosHost"
HARDWARE_ID_LABEL: "mlmec/HardwareID"
HOSTNAME_LABEL: "kubernetes.io/hostname"
DEFAULT_UE_MANAGEMENT_POLICY: "FREE"
MAX_CLIENTS: 200
PRODUCTION_MONGOS_SERVER_IP: '10.210.0.24'
ASSESSMENT_MONGOS_SERVER_IP: '10.190.0.24'
MAIN_MONGO_SHARD_NAME: 'master'
SYSTEM_DATABASE_NAME: 'default'
APPS_COLLECTION_NAME: 'apps'
RESERVED_NAMESPACES: ['default', 'kube-node-lease', 'kube-public', 'kube-system']
DEBUG: False
THREAD_COUNT: 32
DEFAULT_EUCLID_TOPOLOGY_CONFIG: "config/topology-config.yaml"
DEFAULT_PREDICTOR_CONFIG: "./config/predictor-config.yaml"
USE_VIRTUAL_NETWORK_CONTROLLER: False
