AGENT_PORT: 7777
AGENT_HOST: "0.0.0.0"
CLIENT_CONTROLLER_EXTERNAL_PORT: 4444
#CLIENT_CONTROLLER_EXTERNAL_HOST: "10.210.0.20"
CLIENT_CONTROLLER_EXTERNAL_HOST: "0.0.0.0"
MONGOS_PORT: 27017
SHARD_KEY: 'client_id'
